######################################################################
# Automatically generated by qmake (2.01a) Di. Apr 2 01:40:27 2013
######################################################################

TEMPLATE = app
TARGET = compare-files
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += compareLineEdit.h mainwindow.h states.h
SOURCES += main.cpp

ICON = compare-files.icns
RESOURCE_FILES.files = $$ICON
RESOURCE_FILES.path = Contents/Resources
QMAKE_BUNDLE_DATA += RESOURCE_FILES
